### ISSUE TITLE
assertArg should allow lambda to throw checked exceptions

### ISSUE THREAD

**Issue by jypma** [szpak/mockito-java8#12]
When testing code like this (combining mockito + assertJ + mockito-java8), with some assertJ JSON psuedo-code:
```java
    verify(myObject.someMethod(assertArg(s -> {
        assertThat(s).isJSON();
        assertThat(Jackson.parseJSON(s)).hasProperty("foo");   // throws JSONParseException
    });
```
If `Jackson.parseJSON` throws a checked exception, the compiler wants me to catch it inside the lambda. However, that exception should just fail the test, since like any other exception, it means something unexpected has gone wrong.

Hence, I suggest `assertArg` be widened to take a `CheckedConsumer<T>` type:
```java
    @FunctionalInterface
    interface CheckedConsumer<T> {
        void accept(T value) throws Throwable;
    }
```

**Comment by szpak** [comment]
It will be part of 2.5.0 which is unfortunately blocked by https://github.com/travis-ci/travis-ci/issues/9555

**Comment by szpak** [comment]
Being very sad that Travis recommends a VPN as workaround and there is no progress on the Gradle side I just released it self-manually from my workstation (for the first time since I wrote [CDeliveryBoy](https://github.com/szpak/CDeliveryBoy/) to do it for me...).
